### ISSUE TITLE
Feature request: add support for pull_request_target

### ISSUE THREAD

**Issue by rachelleahklein** [unsplash/comment-on-pr#28]
It would be lovely if we could trigger comments on pull requests from forks using the newly minted [`pull_request_target`](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target) workflow event. Please let us know if you plan to add this functionality. Thank you!

**Comment by mikehardy** [comment]
Other actions that fail on fork-based workflows are simply able to move immediately to pull_request_target without further action needed (other than documentation), for example 

https://github.com/amannn/action-semantic-pull-request/pull/25/files

https://github.com/amannn/action-semantic-pull-request/pull/24/files

**Comment by rachelleahklein** [comment]
You're right; on further reflection `pull_request` still meets our needs as well.

Thank you!
