### ISSUE TITLE
Script is not exiting when there's a duplicate comment unless either regex arg is provided

### ISSUE THREAD

**Issue by Jorundur** [unsplash/comment-on-pr#47]
The script should exit (and therefore not add a new comment) if there's a duplicate comment already.

This is done via the `check_duplicate_msg` arg which is `true` by default. I.e. if this is `true` and a duplicate is found, then the script exits.

However, we only check this inside the condition `if !duplicate_msg_pattern.empty? || !delete_prev_regex_msg.empty?`, i.e. either one of those arguments has to exist for the script to exit if there's a duplicate. (https://github.com/unsplash/comment-on-pr/blob/master/entrypoint.sh#L43)

Can this be changed so that it checks for duplicates regardless of the `duplicate_msg_pattern` and `delete_prev_regex_msg` arguments?

See my closed issue https://github.com/unsplash/comment-on-pr/issues/46 for more context for how I got here.

**Comment by aaronklaassen** [comment]
Fixed in #50. Available in `v1.3.1`.
