### ISSUE TITLE
Always fails when opening a PR

### ISSUE THREAD

**Issue by luludan** [unsplash/comment-on-pr#7]
Every time I create a PR I get this error from the the action:
`Couldn't find an open pull request for branch with head at .`

As soon as I push another commit to the branch it works just fine. Seems it may not be using the correct reference to the head commit of the branch?

**Comment by hughgrigg** [comment]
Also getting this, seems hit and miss whether it succeeds or not (detail at https://github.com/unsplash/comment-on-pr/issues/8 )

**Comment by colinhowetab** [comment]
I think the issue here is that people are using this action when they are OPENING a PR and not just pushing a new commit. In this case I think https://github.com/unsplash/comment-on-pr/pull/10/files needs merging.

**Comment by aaronklaassen** [comment]
Fixed by #10. Available in `v1.2.0`
