### ISSUE TITLE
Doesn't work on windows or mac based builds

### ISSUE THREAD

**Issue by jherico** [unsplash/comment-on-pr#9]

**Comment by nuhkoca** [comment]
@jherico did you solve it?

**Comment by jherico** [comment]
@nuhkoca Docker based actions only work on Linux build hosts.  This is not particular to this action, but a "feature" of Github Actions as a whole.  

This feels insane to me, because there's no way in the marketplace to filter out docker based actions, and the only way to see if an action is docker based or not is to go to the source repository.  You can't tell from the detail page in the marketplace.  

This (massive IMO) oversight has led me to largely abandon the marketplace of actions in favor of python scripts.  Why Python isn't a first class language for writing actions in the first place also eludes me.

**Comment by nuhkoca** [comment]
@jherico Thanks for your prompt reply. I strongly agree with you. I am also new to Github Actions and thought we would go running any type of scripts machine-independent but got frustrated. We are unable to mix a variety of scripts altogether.

**Comment by nuhkoca** [comment]
@jherico if you are still curious about it, I have found well-working actions on the marketplace. 

https://github.com/mshick/add-pr-comment

I am using it and it is working as expected. I am receiving comments on PR about failures.
